/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceRouteImport } from './routes/_workspace'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWarehousesRouteImport } from './routes/_app.warehouses'
import { Route as AppUnitsRouteImport } from './routes/_app.units'
import { Route as AppSuppliersRouteImport } from './routes/_app.suppliers'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppOrdersRouteImport } from './routes/_app.orders'
import { Route as AppItemsRouteImport } from './routes/_app.items'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppCustomersRouteImport } from './routes/_app.customers'
import { Route as AppColorsRouteImport } from './routes/_app.colors'
import { Route as AppCategoriesRouteImport } from './routes/_app.categories'
import { Route as WorkspaceItemsNewRouteImport } from './routes/_workspace.items.new'

const WorkspaceRoute = WorkspaceRouteImport.update({
  id: '/_workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWarehousesRoute = AppWarehousesRouteImport.update({
  id: '/warehouses',
  path: '/warehouses',
  getParentRoute: () => AppRoute,
} as any)
const AppUnitsRoute = AppUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => AppRoute,
} as any)
const AppSuppliersRoute = AppSuppliersRouteImport.update({
  id: '/suppliers',
  path: '/suppliers',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRoute,
} as any)
const AppItemsRoute = AppItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppCustomersRoute = AppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AppRoute,
} as any)
const AppColorsRoute = AppColorsRouteImport.update({
  id: '/colors',
  path: '/colors',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriesRoute = AppCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AppRoute,
} as any)
const WorkspaceItemsNewRoute = WorkspaceItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => WorkspaceRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/categories': typeof AppCategoriesRoute
  '/colors': typeof AppColorsRoute
  '/customers': typeof AppCustomersRoute
  '/invoices': typeof AppInvoicesRoute
  '/items': typeof AppItemsRoute
  '/orders': typeof AppOrdersRoute
  '/reports': typeof AppReportsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/units': typeof AppUnitsRoute
  '/warehouses': typeof AppWarehousesRoute
  '/items/new': typeof WorkspaceItemsNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/categories': typeof AppCategoriesRoute
  '/colors': typeof AppColorsRoute
  '/customers': typeof AppCustomersRoute
  '/invoices': typeof AppInvoicesRoute
  '/items': typeof AppItemsRoute
  '/orders': typeof AppOrdersRoute
  '/reports': typeof AppReportsRoute
  '/suppliers': typeof AppSuppliersRoute
  '/units': typeof AppUnitsRoute
  '/warehouses': typeof AppWarehousesRoute
  '/items/new': typeof WorkspaceItemsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_workspace': typeof WorkspaceRouteWithChildren
  '/_app/categories': typeof AppCategoriesRoute
  '/_app/colors': typeof AppColorsRoute
  '/_app/customers': typeof AppCustomersRoute
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/items': typeof AppItemsRoute
  '/_app/orders': typeof AppOrdersRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/suppliers': typeof AppSuppliersRoute
  '/_app/units': typeof AppUnitsRoute
  '/_app/warehouses': typeof AppWarehousesRoute
  '/_workspace/items/new': typeof WorkspaceItemsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/categories'
    | '/colors'
    | '/customers'
    | '/invoices'
    | '/items'
    | '/orders'
    | '/reports'
    | '/suppliers'
    | '/units'
    | '/warehouses'
    | '/items/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/categories'
    | '/colors'
    | '/customers'
    | '/invoices'
    | '/items'
    | '/orders'
    | '/reports'
    | '/suppliers'
    | '/units'
    | '/warehouses'
    | '/items/new'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_workspace'
    | '/_app/categories'
    | '/_app/colors'
    | '/_app/customers'
    | '/_app/invoices'
    | '/_app/items'
    | '/_app/orders'
    | '/_app/reports'
    | '/_app/suppliers'
    | '/_app/units'
    | '/_app/warehouses'
    | '/_workspace/items/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  WorkspaceRoute: typeof WorkspaceRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_workspace': {
      id: '/_workspace'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof WorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/warehouses': {
      id: '/_app/warehouses'
      path: '/warehouses'
      fullPath: '/warehouses'
      preLoaderRoute: typeof AppWarehousesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/units': {
      id: '/_app/units'
      path: '/units'
      fullPath: '/units'
      preLoaderRoute: typeof AppUnitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/suppliers': {
      id: '/_app/suppliers'
      path: '/suppliers'
      fullPath: '/suppliers'
      preLoaderRoute: typeof AppSuppliersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders': {
      id: '/_app/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/items': {
      id: '/_app/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof AppItemsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/customers': {
      id: '/_app/customers'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AppCustomersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/colors': {
      id: '/_app/colors'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof AppColorsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categories': {
      id: '/_app/categories'
      path: '/categories'
      fullPath: '/categories'
      preLoaderRoute: typeof AppCategoriesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_workspace/items/new': {
      id: '/_workspace/items/new'
      path: '/items/new'
      fullPath: '/items/new'
      preLoaderRoute: typeof WorkspaceItemsNewRouteImport
      parentRoute: typeof WorkspaceRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriesRoute: typeof AppCategoriesRoute
  AppColorsRoute: typeof AppColorsRoute
  AppCustomersRoute: typeof AppCustomersRoute
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppItemsRoute: typeof AppItemsRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSuppliersRoute: typeof AppSuppliersRoute
  AppUnitsRoute: typeof AppUnitsRoute
  AppWarehousesRoute: typeof AppWarehousesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriesRoute: AppCategoriesRoute,
  AppColorsRoute: AppColorsRoute,
  AppCustomersRoute: AppCustomersRoute,
  AppInvoicesRoute: AppInvoicesRoute,
  AppItemsRoute: AppItemsRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppReportsRoute: AppReportsRoute,
  AppSuppliersRoute: AppSuppliersRoute,
  AppUnitsRoute: AppUnitsRoute,
  AppWarehousesRoute: AppWarehousesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface WorkspaceRouteChildren {
  WorkspaceItemsNewRoute: typeof WorkspaceItemsNewRoute
}

const WorkspaceRouteChildren: WorkspaceRouteChildren = {
  WorkspaceItemsNewRoute: WorkspaceItemsNewRoute,
}

const WorkspaceRouteWithChildren = WorkspaceRoute._addFileChildren(
  WorkspaceRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  WorkspaceRoute: WorkspaceRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
